version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: teste
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    command: sh -c './wait-for.sh db:5432 -t 60 -- npm start'
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db